name: matt_murdock
description: flutter Portafolio.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

# media
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0

# navigation
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  # icons
  flutter_launcher_icons: "^0.9.2"



flutter:

  uses-material-design: true
  assets:
   - assets/navigation_bar/
   - assets/socials/
   - assets/mock/
   - assets/images/
   - assets/expertise_logo/

  # font assets
  fonts:
    - family: gothic
      fonts:
        - asset: assets/font/gothic/Century Gothic.ttf
        - asset: assets/font/gothic/CenturyGothic.ttf
        - asset: assets/font/gothic/GOTHIC.TTF
        - asset: assets/font/gothic/gothicb.ttf
        - asset: assets/font/gothic/GOTHICB0.TTF

 
